### ISSUE TITLE
Create Basic Styling for Landing Page

### ISSUE THREAD

**Issue by OSP123** [OSP123/myspace-lookup-tool#10]
User Story: As a end user, I would like to see a nicely styled page when I go to the application, so that I can have a better user experience when interacting with the application. 

Acceptance Criteria:

- [x] Determine which CSS library to use in order to structure and style the application
- [x] Make sure that the application is responsive
- [x] All the HTML that is seen by the user should be appropriately styled
