### ISSUE TITLE
Search Capability

### ISSUE THREAD

**Issue by OSP123** [OSP123/myspace-lookup-tool#6]
User Story: As an end user, I would like to the ability to search for my profile based on user info, so that I can see my profile information. 

Acceptance Criteria:

- [ ] Search bar should be intuitive for end users
- [ ] Search bar should take in username, email, location, and/or email to search for data about user. Could use fuzzy searching for getting data about user from partial data, like partial usernames
- [ ] Information sent via the search bar should return with a response of data about the user or an error message if the information wasn't found
