### ISSUE TITLE
Determine How Best to display MySpace Page based on User Input

### ISSUE THREAD

**Issue by OSP123** [OSP123/myspace-lookup-tool#7]
User Story: As a developer, I would like to determine how best to display the MySpace Page to the user, so that the user has an easy way of looking at their MySpace page.

Acceptance Criteria:
- [ ] Results from the search should first be displayed to the user in order for the user to determine if the information returned matches their identity. 
- [ ] Search Way Back Machine APIs and similar technology to see if we can pass the data to the api and display the actual page into our application. 
- [ ] If that doesn't work, then check to see what options there are for building static urls for the Way Back Machine based on the years the profile existed. We can then display that information to the page within an Iframe. MVP should be one year. Determining year can be a task of its own.
