### ISSUE TITLE
Create Static Landing Page

### ISSUE THREAD

**Issue by OSP123** [OSP123/myspace-lookup-tool#8]
User Story: As a Developer, I would like to create a static lnading page, so that I can have a starting point for the application.

Acceptance Criteria:

- [ ] Should contain all the relevant static HTML for a landing page
- [ ] Styling should match overall goals and be separated into its own file
- [ ] Should contain a navigation menu with About Us and Registration/Login
- [ ] Should be responsive
- [ ] Should contain a search form
- [ ] Should contain instructions for using the search form
- [ ] Should have HTML that will display the results, if needed.
